services:
  db:
    image: postgres:15-alpine
    container_name: finance_tracker_db
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
      POSTGRES_DB: finance_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user -d finance_tracker"]
      interval: 5s
      timeout: 3s
      retries: 5

#  app:
#    build: .
#    container_name: finance_tracker_app
#    env_file:
#      - .env.dev
#    environment:
#      POSTGRES_SERVER: db
#    ports:
#      - "8020:8000"
#    depends_on:
#      db:
#        condition: service_healthy

volumes:
  postgres_data: