"""add transfer kind and transfer_group_id

Revision ID: 1bb92b3f825f
Revises: 0e0bbd0a4943
Create Date: 2026-08-02 23:18:38.783036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb92b3f825f'
down_revision: Union[str, Sequence[str], None] = '0e0bbd0a4943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE transactionkind ADD VALUE IF NOT EXISTS 'TRANSFER'")

    op.add_column('transactions', sa.Column('transfer_group_id', sa.Uuid(), nullable=True))
    op.create_index('ix_transactions_transfer_group_id', 'transactions', ['transfer_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_transfer_group_id', table_name='transactions')
    op.drop_column('transactions', 'transfer_group_id')
    # 'TRANSFER' stays in the transactionkind type: PostgreSQL cannot remove enum
    # values, and recreating the type costs more than an unused label
    # ### end Alembic commands ###
