"""add transaction_template_splits

Revision ID: 59b48a6df158
Revises: 9db60f3af6aa
Create Date: 2026-08-30 20:41:30.267318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b48a6df158'
down_revision: Union[str, Sequence[str], None] = '9db60f3af6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_template_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_template_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='check_transaction_template_split_amount_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_template_id'], ['transaction_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_template_splits_category_id', 'transaction_template_splits', ['category_id'], unique=False)
    op.create_index('ix_transaction_template_splits_transaction_template_id', 'transaction_template_splits', ['transaction_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_template_splits_transaction_template_id', table_name='transaction_template_splits')
    op.drop_index('ix_transaction_template_splits_category_id', table_name='transaction_template_splits')
    op.drop_table('transaction_template_splits')
    # ### end Alembic commands ###
