"""add transaction account_id

Revision ID: 60a303708cd0
Revises: 19840b0a6cf6
Create Date: 2026-07-28 14:07:15.537994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a303708cd0'
down_revision: Union[str, Sequence[str], None] = '19840b0a6cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index('ix_transactions_account_id_date', 'transactions', ['account_id', 'date'], unique=False)
    op.create_foreign_key(
        'fk_transactions_account_id', 'transactions', 'accounts', ['account_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_account_id', 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_account_id_date', table_name='transactions')
    op.drop_column('transactions', 'account_id')
    # ### end Alembic commands ###
