"""add transaction_splits table

Revision ID: 9db60f3af6aa
Revises: fb292ab1bb42
Create Date: 2026-08-20 20:31:25.531687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db60f3af6aa'
down_revision: Union[str, Sequence[str], None] = 'fb292ab1bb42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='check_transaction_split_amount_non_negative'),
    sa.CheckConstraint('settled_amount >= 0', name='check_transaction_split_settled_amount_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_splits_category_id', 'transaction_splits', ['category_id'], unique=False)
    op.create_index('ix_transaction_splits_transaction_id', 'transaction_splits', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_splits_transaction_id', table_name='transaction_splits')
    op.drop_index('ix_transaction_splits_category_id', table_name='transaction_splits')
    op.drop_table('transaction_splits')
    # ### end Alembic commands ###
