"""add transaction kind

Revision ID: c75ba8ee8757
Revises: 3916e3c74c84
Create Date: 2026-07-27 20:11:27.391491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75ba8ee8757'
down_revision: Union[str, Sequence[str], None] = '3916e3c74c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    transaction_kind = sa.Enum('REGULAR', 'ADJUSTMENT', name='transactionkind')
    transaction_kind.create(op.get_bind())

    op.add_column(
        'transactions',
        sa.Column('kind', transaction_kind, nullable=True),  # 1. nullable
    )
    op.execute("UPDATE transactions SET kind = 'REGULAR'")  # 2. backfill
    op.alter_column('transactions', 'kind', nullable=False)  # 3. NOT NULL
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'kind')
    sa.Enum(name='transactionkind').drop(op.get_bind())
    # ### end Alembic commands ###
