"""add password changed at to users

Revision ID: d9da74d03578
Revises: 59b48a6df158
Create Date: 2026-09-12 23:14:19.189855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd9da74d03578'
down_revision: Union[str, Sequence[str], None] = '59b48a6df158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))

    op.execute("UPDATE users SET password_changed_at = created_at")
    op.alter_column('users', 'password_changed_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    # ### end Alembic commands ###
