"""add_performance_indexes_and_timezone_aware_datetime

Revision ID: ebe6a7650a2e
Revises: 9f848df00430
Create Date: 2026-04-15 23:36:18.558246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebe6a7650a2e'
down_revision: Union[str, Sequence[str], None] = '9f848df00430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'archived_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True,
                    postgresql_using="archived_at AT TIME ZONE 'UTC'")
    op.alter_column('categories', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False,
                    postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.create_index('ix_categories_user_id', 'categories', ['user_id'], unique=False)
    op.alter_column('transaction_templates', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False,
                    postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.drop_constraint(op.f('uq_user_template_name'), 'transaction_templates', type_='unique')
    op.create_index('ix_transaction_templates_user_id', 'transaction_templates', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_transaction_template_name', 'transaction_templates', ['user_id', 'name'])
    op.create_index('ix_transactions_category_id', 'transactions', ['category_id'], unique=False)
    op.create_index('ix_transactions_user_id_date', 'transactions', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_id_date', table_name='transactions')
    op.drop_index('ix_transactions_category_id', table_name='transactions')
    op.drop_constraint('uq_user_transaction_template_name', 'transaction_templates', type_='unique')
    op.drop_index('ix_transaction_templates_user_id', table_name='transaction_templates')
    op.create_unique_constraint(op.f('uq_user_template_name'), 'transaction_templates', ['user_id', 'name'],
                                postgresql_nulls_not_distinct=False)
    op.alter_column('transaction_templates', 'created_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False,
                    postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.drop_index('ix_categories_user_id', table_name='categories')
    op.alter_column('categories', 'created_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False,
                    postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('categories', 'archived_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True,
                    postgresql_using="archived_at AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###
